name: Test C Binding

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config uuid-dev
      - name: Build Minijinja C library
        working-directory: "c"
        run: cargo build
      - name: Build Test Framework
        working-directory: c
        run: |
          mkdir build
          cd build
          cmake ..
          make -j$(nproc) tests
      - name: Run Tests
        working-directory: c/build
        run: ./tests
